package com.example.ui.localization

import androidx.compose.runtime.compositionLocalOf
import androidx.compose.ui.unit.LayoutDirection

enum class AppLanguage {
  FA, // Persian (Farsi) - Default
  EN  // English
}

data class Strings(
  val appName: String,
  val appSubtitle: String,
  val appVersion: String,
  val appDeveloper: String,
  val splashLoading: String,

  // Nav
  val navDashboard: String,
  val navProjects: String,
  val navStarred: String,
  val navRecent: String,
  val navSettings: String,

  // Common
  val cancel: String,
  val confirm: String,
  val save: String,
  val saved: String,
  val delete: String,
  val edit: String,
  val create: String,
  val search: String,
  val open: String,
  val close: String,
  val share: String,
  val export: String,
  val `import`: String,
  val copy: String,
  val copied: String,
  val paste: String,
  val cut: String,
  val selectAll: String,
  val undo: String,
  val redo: String,
  val restore: String,
  val star: String,
  val unstar: String,
  val duplicate: String,
  val rename: String,
  val move: String,
  val options: String,
  val back: String,
  val viewAll: String,
  val items: String,
  val bytes: String,
  val kb: String,
  val mb: String,
  val emptyStateTitle: String,
  val emptyStateDesc: String,
  val success: String,
  val error: String,
  val warning: String,

  // Dashboard
  val dashboardTitle: String,
  val quickActions: String,
  val newProject: String,
  val importZip: String,
  val backupNow: String,
  val storageOverview: String,
  val totalProjects: String,
  val totalFiles: String,
  val totalFolders: String,
  val recentProjects: String,
  val starredProjects: String,
  val searchPlaceholder: String,
  val noProjectsYet: String,
  val createFirstProject: String,

  // Projects
  val projectsTitle: String,
  val projectName: String,
  val projectDesc: String,
  val projectType: String,
  val createProject: String,
  val projectDetails: String,
  val openProjectExplorer: String,
  val lastModified: String,
  val deleteProjectConfirm: String,
  val exportAsZip: String,

  // Explorer
  val fileExplorer: String,
  val newFolder: String,
  val newFile: String,
  val folderName: String,
  val fileName: String,
  val fileExtension: String,
  val emptyFolder: String,
  val deleteItemConfirm: String,
  val renameItem: String,
  val moveItem: String,

  // Editor
  val codeEditor: String,
  val copyAllCode: String,
  val copySelection: String,
  val copyLine: String,
  val duplicateLine: String,
  val goToLine: String,
  val linePrompt: String,
  val findAndReplace: String,
  val find: String,
  val replace: String,
  val replaceAll: String,
  val autoIndent: String,
  val wordWrap: String,
  val lineNumbers: String,
  val line: String,
  val column: String,
  val chars: String,
  val autoSaved: String,

  // Search
  val searchTitle: String,
  val searchScope: String,
  val scopeAllProjects: String,
  val scopeCurrentProject: String,
  val scopeFileNames: String,
  val scopeCodeContent: String,
  val searchResults: String,
  val noResultsFound: String,
  val matchFound: String,

  // Starred
  val starredTitle: String,
  val starredFiles: String,

  // Recent
  val recentTitle: String,
  val recentFiles: String,
  val noRecentFiles: String,

  // Trash
  val trashTitle: String,
  val trashEmpty: String,
  val emptyTrash: String,
  val emptyTrashConfirm: String,
  val restoreItem: String,
  val deletePermanently: String,
  val deletePermanentConfirm: String,
  val trashedOn: String,

  // Version History
  val versionHistoryTitle: String,
  val noVersions: String,
  val restoreVersion: String,
  val restoreVersionConfirm: String,
  val currentVersion: String,
  val snapshotTakenAt: String,
  val previewVersion: String,

  // Backup & Storage
  val backupTitle: String,
  val backupAllProjects: String,
  val backupSingleProject: String,
  val restoreBackup: String,
  val backupHistory: String,
  val storageTitle: String,
  val projectsSize: String,
  val trashSize: String,
  val backupsSize: String,
  val clearCache: String,
  val cacheCleared: String,

  // Settings
  val settingsTitle: String,
  val appearance: String,
  val language: String,
  val editorSettings: String,
  val vipSubscription: String,
  val aboutApp: String,
  val privacyPolicy: String,
  val termsOfService: String,
  val themeMetallicBlack: String,
  val themeLight: String,
  val themeAmoled: String,
  val themeMidnight: String,
  val themeGraphite: String,
  val themeCyber: String,
  val fontSize: String,
  val tabSize: String,
  val autoSaveInterval: String,
  val syntaxHighlighting: String,

  // VIP & Ads
  val vipTitle: String,
  val vipBadge: String,
  val vipActive: String,
  val vipFeature1: String,
  val vipFeature2: String,
  val vipFeature3: String,
  val vipFeature4: String,
  val vipFeature5: String,
  val vipFeature6: String,
  val upgradeToVip: String,
  val planMonthly: String,
  val planYearly: String,
  val planLifetime: String,
  val restorePurchase: String,
  val restorePurchaseSuccess: String,
  val purchaseSuccess: String,
  val adSponsored: String,
  val watchAdToUnlock: String,

  // About
  val aboutDesc: String,
  val copyright: String
)

val PersianStrings = Strings(
  appName = "CodeVault",
  appSubtitle = "مدیریت حرفه‌ای پروژه و کد",
  appVersion = "نسخه ۱.۰.۰",
  appDeveloper = "سیدحمید موسوی زاده",
  splashLoading = "در حال راه‌اندازی مخزن کدهای شما...",

  navDashboard = "داشبورد",
  navProjects = "پروژه‌ها",
  navStarred = "نشان‌شده",
  navRecent = "اخیر",
  navSettings = "تنظیمات",

  cancel = "انصراف",
  confirm = "تأیید",
  save = "ذخیره",
  saved = "تغییرات ذخیره شد",
  delete = "حذف",
  edit = "ویرایش",
  create = "ایجاد",
  search = "جستجو",
  open = "باز کردن",
  close = "بستن",
  share = "اشتراک‌گذاری",
  export = "خروجی",
  `import` = "وارد کردن",
  copy = "کپی",
  copied = "کپی شد در حافظه",
  paste = "جای‌گذاری",
  cut = "برش",
  selectAll = "انتخاب همه",
  undo = "بازگشت",
  redo = "تکرار",
  restore = "بازیابی",
  star = "افزودن به ستاره‌ها",
  unstar = "حذف از ستاره‌ها",
  duplicate = "تکثیر",
  rename = "تغییر نام",
  move = "انتقال",
  options = "گزینه‌ها",
  back = "بازگشت",
  viewAll = "مشاهده همه",
  items = "مورد",
  bytes = "بایت",
  kb = "کیلوبایت",
  mb = "مگابایت",
  emptyStateTitle = "موردی یافت نشد",
  emptyStateDesc = "برای شروع روی دکمه افزودن ضربه بزنید",
  success = "عملیات با موفقیت انجام شد",
  error = "خطایی رخ داد",
  warning = "هشدار",

  dashboardTitle = "میز کار CodeVault",
  quickActions = "دسترسی سریع",
  newProject = "پروژه جدید",
  importZip = "وارد کردن ZIP",
  backupNow = "پشتیبان‌گیری",
  storageOverview = "وضعیت حافظه مخزن",
  totalProjects = "پروژه‌ها",
  totalFiles = "فایل‌ها",
  totalFolders = "پوشه‌ها",
  recentProjects = "پروژه‌های اخیر",
  starredProjects = "پروژه‌های نشان‌شده",
  searchPlaceholder = "جستجو در کدها و پروژه‌ها...",
  noProjectsYet = "هنوز پروژه‌ای ایجاد نکرده‌اید",
  createFirstProject = "ایجاد اولین پروژه",

  projectsTitle = "همه پروژه‌ها",
  projectName = "نام پروژه",
  projectDesc = "توضیحات پروژه (اختیاری)",
  projectType = "قالب / زبان اصلی",
  createProject = "ایجاد پروژه",
  projectDetails = "مشخصات پروژه",
  openProjectExplorer = "باز کردن پروژه و فایل‌ها",
  lastModified = "آخرین تغییر:",
  deleteProjectConfirm = "آیا از انتقال این پروژه به سطل زباله اطمینان دارید؟",
  exportAsZip = "خروجی کامل به صورت ZIP",

  fileExplorer = "کاوشگر فایل",
  newFolder = "پوشه جدید",
  newFile = "فایل جدید",
  folderName = "نام پوشه",
  fileName = "نام فایل (همراه با پسوند)",
  fileExtension = "پسوند فایل (مثلاً kt, py, js)",
  emptyFolder = "این پوشه خالی است",
  deleteItemConfirm = "آیا از انتقال این مورد به سطل زباله اطمینان دارید؟",
  renameItem = "تغییر نام",
  moveItem = "انتقال به پوشه دیگر",

  codeEditor = "ویرایشگر کد",
  copyAllCode = "کپی کل کد",
  copySelection = "کپی بخش انتخابی",
  copyLine = "کپی این خط",
  duplicateLine = "تکثیر خط",
  goToLine = "برو به شماره خط",
  linePrompt = "شماره خط مورد نظر را وارد کنید:",
  findAndReplace = "جستجو و جایگزینی",
  find = "جستجو",
  replace = "جایگزینی",
  replaceAll = "جایگزینی همه",
  autoIndent = "فاصله‌گذاری خودکار",
  wordWrap = "شکستن خطوط طولانی",
  lineNumbers = "شماره خطوط",
  line = "خط",
  column = "ستون",
  chars = "نویسه",
  autoSaved = "ذخیره خودکار فعال است",

  searchTitle = "جستجوی جامع",
  searchScope = "محدوده جستجو",
  scopeAllProjects = "تمام پروژه‌ها",
  scopeCurrentProject = "پروژه جاری",
  scopeFileNames = "نام فایل‌ها و پوشه‌ها",
  scopeCodeContent = "محتوای کدهای منبع",
  searchResults = "نتایج جستجو",
  noResultsFound = "هیچ نتیجه‌ای مطابق عبارت پیدا نشد",
  matchFound = "تطابق در خط",

  starredTitle = "موارد نشان‌شده",
  starredFiles = "فایل‌های ستاره‌دار",

  recentTitle = "فایل‌های اخیر",
  recentFiles = "فایل‌های اخیراً باز شده",
  noRecentFiles = "هیچ فایلی اخیراً باز نشده است",

  trashTitle = "سطل زباله",
  trashEmpty = "سطل زباله خالی است",
  emptyTrash = "تخلیه کامل سطل زباله",
  emptyTrashConfirm = "آیا از حذف دائمی تمام موارد سطل زباله اطمینان دارید؟ این عمل غیرقابل بازگشت است.",
  restoreItem = "بازیابی به محل اصلی",
  deletePermanently = "حذف دائمی",
  deletePermanentConfirm = "آیا مطمئن هستید؟ این مورد برای همیشه حذف خواهد شد.",
  trashedOn = "حذف شده در:",

  versionHistoryTitle = "تاریخچه نسخه‌های فایل",
  noVersions = "هنوز نسخه‌ای برای این فایل ثبت نشده است",
  restoreVersion = "بازیابی به این نسخه",
  restoreVersionConfirm = "آیا می‌خواهید محتوای فایل به این نسخه بازگردد؟",
  currentVersion = "نسخه جاری",
  snapshotTakenAt = "ثبت شده در:",
  previewVersion = "پیش‌نمایش نسخه",

  backupTitle = "پشتیبان‌گیری و بازیابی",
  backupAllProjects = "پشتیبان‌گیری از تمام پروژه‌ها",
  backupSingleProject = "پشتیبان‌گیری از این پروژه",
  restoreBackup = "بازیابی فایل پشتیبان",
  backupHistory = "پشتیبان‌های ذخیره شده",
  storageTitle = "مدیریت حافظه",
  projectsSize = "حجم کل پروژه‌ها",
  trashSize = "حجم سطل زباله",
  backupsSize = "حجم پشتیبان‌ها",
  clearCache = "پاکسازی حافظه پنهان موقت",
  cacheCleared = "حافظه موقت با موفقیت پاک شد",

  settingsTitle = "تنظیمات مخزن",
  appearance = "ظاهر و پوسته",
  language = "زبان برنامه (Language)",
  editorSettings = "تنظیمات ویرایشگر کد",
  vipSubscription = "اشتراک ویژه VIP",
  aboutApp = "درباره CodeVault",
  privacyPolicy = "سیاست حفظ حریم خصوصی",
  termsOfService = "شرایط استفاده و قوانین",
  themeMetallicBlack = "مشکی متالیک (پیش‌فرض)",
  themeLight = "روشن (Light)",
  themeAmoled = "تاریک مطلق (AMOLED)",
  themeMidnight = "سرمه‌ای شب (Midnight)",
  themeGraphite = "گرافیتی مات (Graphite)",
  themeCyber = "سایبر نئون (Cyber)",
  fontSize = "اندازه قلم ویرایشگر",
  tabSize = "تعداد فاصله‌های Tab",
  autoSaveInterval = "فاصله ذخیره خودکار",
  syntaxHighlighting = "رنگ‌آمیزی دستورات (Syntax)",

  vipTitle = "عضویت طلایی CodeVault VIP",
  vipBadge = "کاربر ویژه VIP",
  vipActive = "اشتراک VIP شما فعال است",
  vipFeature1 = "ایجاد نامحدود پروژه و فایل",
  vipFeature2 = "سیستم پیشرفته تاریخچه نسخه‌ها با مقایسه تغییرات",
  vipFeature3 = "پشتیبان‌گیری چندگانه و فشرده‌سازی پرسرعت",
  vipFeature4 = "حذف کامل تمام تبلیغات در سراسر برنامه",
  vipFeature5 = "پوسته‌ها و فونت‌های برنامه‌نویسی اختصاصی",
  vipFeature6 = "جستجوی پیشرفته با رجکس (Regex) در کل مخزن",
  upgradeToVip = "ارتقا به اشتراک طلایی VIP",
  planMonthly = "اشتراک ۱ ماهه",
  planYearly = "اشتراک ۱ ساله (به‌صرفه)",
  planLifetime = "اشتراک مادام‌العمر (یک‌بار پرداخت)",
  restorePurchase = "بازیابی خرید قبلی",
  restorePurchaseSuccess = "وضعیت خرید با موفقیت بررسی و فعال شد",
  purchaseSuccess = "با تشکر! اشتراک VIP شما با موفقیت فعال گردید",
  adSponsored = "حمایت مالی و تبلیغات",
  watchAdToUnlock = "مشاهده تبلیغ ویدیویی برای باز شدن قابلیت",

  aboutDesc = "CodeVault یک محیط مدیریت و توسعه کامل پروژه و کد برای توسعه‌دهندگان اندروید است. این اپلیکیشن با معماری بومی Local-first طراحی شده تا تمام فایل‌ها و کدهای شما به طور امن در دستگاه شما نگهداری شوند.",
  copyright = "تمامی حقوق محفوظ است © ۱۴۰۵ - سیدحمید موسوی زاده"
)

val EnglishStrings = Strings(
  appName = "CodeVault",
  appSubtitle = "Professional Code & Project Manager",
  appVersion = "Version 1.0.0",
  appDeveloper = "Seyyed Hamid Mousavi Zadeh",
  splashLoading = "Initializing your code repository...",

  navDashboard = "Dashboard",
  navProjects = "Projects",
  navStarred = "Starred",
  navRecent = "Recent",
  navSettings = "Settings",

  cancel = "Cancel",
  confirm = "Confirm",
  save = "Save",
  saved = "Changes saved",
  delete = "Delete",
  edit = "Edit",
  create = "Create",
  search = "Search",
  open = "Open",
  close = "Close",
  share = "Share",
  export = "Export",
  `import` = "Import",
  copy = "Copy",
  copied = "Copied to clipboard",
  paste = "Paste",
  cut = "Cut",
  selectAll = "Select All",
  undo = "Undo",
  redo = "Redo",
  restore = "Restore",
  star = "Star",
  unstar = "Unstar",
  duplicate = "Duplicate",
  rename = "Rename",
  move = "Move",
  options = "Options",
  back = "Back",
  viewAll = "View All",
  items = "items",
  bytes = "B",
  kb = "KB",
  mb = "MB",
  emptyStateTitle = "Nothing here yet",
  emptyStateDesc = "Tap the button below to get started",
  success = "Operation successful",
  error = "An error occurred",
  warning = "Warning",

  dashboardTitle = "CodeVault Dashboard",
  quickActions = "Quick Actions",
  newProject = "New Project",
  importZip = "Import ZIP",
  backupNow = "Backup",
  storageOverview = "Vault Storage Overview",
  totalProjects = "Projects",
  totalFiles = "Files",
  totalFolders = "Folders",
  recentProjects = "Recent Projects",
  starredProjects = "Starred Projects",
  searchPlaceholder = "Search code and projects...",
  noProjectsYet = "No projects created yet",
  createFirstProject = "Create First Project",

  projectsTitle = "All Projects",
  projectName = "Project Name",
  projectDesc = "Description (Optional)",
  projectType = "Template / Primary Language",
  createProject = "Create Project",
  projectDetails = "Project Details",
  openProjectExplorer = "Open Project Explorer",
  lastModified = "Last modified:",
  deleteProjectConfirm = "Move this project to trash?",
  exportAsZip = "Export as complete ZIP",

  fileExplorer = "File Explorer",
  newFolder = "New Folder",
  newFile = "New File",
  folderName = "Folder Name",
  fileName = "File Name (with extension)",
  fileExtension = "File extension (e.g. kt, py, js)",
  emptyFolder = "This folder is empty",
  deleteItemConfirm = "Move this item to trash?",
  renameItem = "Rename",
  moveItem = "Move to folder",

  codeEditor = "Code Editor",
  copyAllCode = "Copy All Code",
  copySelection = "Copy Selection",
  copyLine = "Copy Line",
  duplicateLine = "Duplicate Line",
  goToLine = "Go to Line",
  linePrompt = "Enter target line number:",
  findAndReplace = "Find & Replace",
  find = "Find",
  replace = "Replace",
  replaceAll = "Replace All",
  autoIndent = "Auto Indentation",
  wordWrap = "Word Wrap",
  lineNumbers = "Line Numbers",
  line = "Ln",
  column = "Col",
  chars = "chars",
  autoSaved = "Auto-save active",

  searchTitle = "Repository Search",
  searchScope = "Search Scope",
  scopeAllProjects = "All Projects",
  scopeCurrentProject = "Current Project",
  scopeFileNames = "File & Folder Names",
  scopeCodeContent = "Source Code Content",
  searchResults = "Search Results",
  noResultsFound = "No matching items found",
  matchFound = "Match at line",

  starredTitle = "Starred Items",
  starredFiles = "Starred Files",

  recentTitle = "Recent Files",
  recentFiles = "Recently opened files",
  noRecentFiles = "No recent files recorded",

  trashTitle = "Recycle Bin",
  trashEmpty = "Trash is empty",
  emptyTrash = "Empty Trash",
  emptyTrashConfirm = "Are you sure you want to permanently delete all items in trash? This cannot be undone.",
  restoreItem = "Restore to original location",
  deletePermanently = "Delete Permanently",
  deletePermanentConfirm = "Are you sure? This item will be erased forever.",
  trashedOn = "Trashed on:",

  versionHistoryTitle = "File Version History",
  noVersions = "No snapshot versions recorded yet",
  restoreVersion = "Restore this version",
  restoreVersionConfirm = "Restore the file content to this snapshot?",
  currentVersion = "Current Version",
  snapshotTakenAt = "Recorded at:",
  previewVersion = "Preview Version",

  backupTitle = "Backup & Restore",
  backupAllProjects = "Backup All Projects",
  backupSingleProject = "Backup This Project",
  restoreBackup = "Restore from ZIP Backup",
  backupHistory = "Saved Backups",
  storageTitle = "Storage Manager",
  projectsSize = "Total Projects Size",
  trashSize = "Trash Size",
  backupsSize = "Backups Size",
  clearCache = "Clear Temporary Cache",
  cacheCleared = "Temporary cache cleared successfully",

  settingsTitle = "Vault Settings",
  appearance = "Appearance & Theme",
  language = "Language",
  editorSettings = "Code Editor Settings",
  vipSubscription = "VIP Subscription",
  aboutApp = "About CodeVault",
  privacyPolicy = "Privacy Policy",
  termsOfService = "Terms of Service",
  themeMetallicBlack = "Metallic Black (Default)",
  themeLight = "Light",
  themeAmoled = "Pure AMOLED",
  themeMidnight = "Midnight Navy",
  themeGraphite = "Matte Graphite",
  themeCyber = "Cyber Neon",
  fontSize = "Editor Font Size",
  tabSize = "Tab Indent Spaces",
  autoSaveInterval = "Auto-Save Interval",
  syntaxHighlighting = "Syntax Highlighting",

  vipTitle = "CodeVault VIP Membership",
  vipBadge = "VIP Member",
  vipActive = "Your VIP Subscription is Active",
  vipFeature1 = "Unlimited projects & code files",
  vipFeature2 = "Advanced multi-version snapshots",
  vipFeature3 = "High-speed multi-backup archives",
  vipFeature4 = "100% ad-free experience",
  vipFeature5 = "Exclusive developer themes & fonts",
  vipFeature6 = "Regex-powered multi-file code search",
  upgradeToVip = "Upgrade to VIP Gold",
  planMonthly = "Monthly Subscription",
  planYearly = "Yearly Subscription (Best Value)",
  planLifetime = "Lifetime Pass (One-time)",
  restorePurchase = "Restore Purchases",
  restorePurchaseSuccess = "Purchase status verified and restored",
  purchaseSuccess = "Thank you! VIP membership is now activated",
  adSponsored = "Sponsored Ad",
  watchAdToUnlock = "Watch rewarded video to unlock",

  aboutDesc = "CodeVault is a full-fledged native Android developer code & project management suite. Built strictly local-first to ensure 100% security, privacy, and full offline functionality for your source code.",
  copyright = "All Rights Reserved © 2026 - Seyyed Hamid Mousavi Zadeh"
)

val LocalAppStrings = compositionLocalOf { PersianStrings }
val LocalAppLanguage = compositionLocalOf { AppLanguage.FA }

fun getStrings(language: AppLanguage): Strings = when (language) {
  AppLanguage.FA -> PersianStrings
  AppLanguage.EN -> EnglishStrings
}

fun getLayoutDirection(language: AppLanguage): LayoutDirection = when (language) {
  AppLanguage.FA -> LayoutDirection.Rtl
  AppLanguage.EN -> LayoutDirection.Ltr
}
